### ISSUE TITLE
How to deploy this to production

### ISSUE THREAD

**Issue by xvpc** [warren-bank/HLS-Proxy#29] opened 2023-03-30 03:19 UTC
Hi, I have used this Proxy for a couple of days now and works fine with me, But when I try to host it or deploy it into a real word application it doesn't seem to work, I'm using Github Action and Yml to start the proxy using `npm start` but when I make my Github page and try to navigate to it or test the Proxy with an m3u8 file It redirects me to a notFound page Aka 404.
How can I get it to work on my Github actions what I'm doing wrong and how can I fix the Problem?
Thank you.

- Update:
Hi, @warren-bank  I posted my Problem on StateOverFlow There I mentioned More details of the problem and what I tried to do Please Check it out. 
https://stackoverflow.com/questions/75883924/how-to-deploy-proxy-to-production

**Comment by warren-bank** [comment] 2023-03-30 18:41
closing as a duplicate of #20 .. will add some comments there.

**Closed as completed by warren-bank** 2023-03-30 18:41 UTC
